name: Spotify

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Spotify
        uses: novatorem/spotify-recently-played@main
        with:
          user_id: YOUR_SPOTIFY_ID
          client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      - uses: stefanzweifel/git-auto-commit-action@v4